### ISSUE TITLE
Spams this error

### ISSUE THREAD

**Issue by SheepCommander** [TaiAurori/no-insta-join#1]
![image](https://user-images.githubusercontent.com/66646514/148925952-8a27f396-ea63-4f41-b8a5-c26fae36ad77.png)

Also is the plugin supposed to give you confirmation when you click a `discord.gg/` link, or is it supposed to straight up prevent you from joining when you click a `discord.gg/` link?

**Comment by TaiAurori** [comment]
1. Supposed to show the server invite page you see when you open a server invite in the browser instead of instantly joining you.
2. Unable to repro, unsure what's happening here.
